[package]
name = "ybyra"
version = "0.1.0"
edition = "2021"

[dependencies]
git2 = "0.19.0"
rocket = { version = "0.5.1", features = ["http2", "json"] }
rocket_dyn_templates = { version = "0.2.0", features = ["tera"] }
tera = "1.20.0"
